import streamlit
streamlit.title("My Parents New Healthy Dinner")
streamlit.header('Breakfast Menu')
streamlit.text('Omega 3 & Blueberry Oatmeal')
streamlit.text('Kale, Spinach & Rocket Smoothie')
streamlit.text('Hard-Boiled Free-Range Egg')
streamlit.header("Todays Lunch Menu")
streamlit.text("Dal and Rice")
streamlit.text("fish and Rice")
streamlit.text("Utpam")
